<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="NB-003934" ignored="0" name="Command line test" tests="6" failures="1" timestamp="18 Sep 2018 22:19:11 GMT" time="42.753" errors="0">
  <testcase name="feature" time="13.651" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="feature" time="5.715" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="feature" time="12.347" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="feature" time="3.472" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="feature" time="3.441" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="feature" time="3.443" classname="cucumber.api.testng.AbstractTestNGCucumberTests">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: A validacao do PUT para esta API falhou, por favor verifique">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: A validacao do PUT para esta API falhou, por favor verifique
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
Caused by: java.lang.AssertionError: A validacao do PUT para esta API falhou, por favor verifique
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.assertTrue(Assert.java:41)
at steps.IndicadorSteps.validarEnvioPutApiIndicador(IndicadorSteps.java:152)
at âœ½.Entao valido se o put foi enviado com sucesso para a api indicador(src/test/resources/indicador/ValidaPutIndicador.feature:10)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- Command line test -->
